[[language]]
name = "elixir"
auto-format = true

[[language]]
name = "heex"
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettierd', args = [".js"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettierd', args = [".ts"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettierd', args = [".jsx"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettierd', args = [".tsx"] }
auto-format = true

[[language]]
auto-format = true
name = "c-sharp"
formatter = { command = "csharpier" }

[language-server.omnisharp]
command = "dotnet"
args = [ "/home/rlillo/tools/omnisharp/OmniSharp.dll", "--languageserver" ]
timeout = 60
